### PR TITLE
feat: stops creation of log files by default

### PR DESCRIPTION
**Pull request by siowyisheng**
tested on windows

### CODE REVIEW

**Comment by kensoh** [comment]
👍 some comments -

1. feel free to commit direct to v6 branch without PRs because that should improve dev speed, unless there are some changes which you want me to review or discuss first.. Then PR, or whatsapp etc, whichever is the easiest for your workflow.

2. There's a section in readme with `Click to show info on automation logs (.log, .js, .raw), and how to run tagui from any directory` which also talks about the default logging files, that section also requires updating. And because the [tutorial doc](https://github.com/kelaberetiv/TagUI/blob/master/src/media/RPA%20Workshop.md) is base on readme, these changes also have to copy there. Which is very 🤦‍♂.... right....

3. In `tagui` file, recommend to change to below. Both works, just that below is consistent with the style in the existing script when not is used, for readability -
```
if ! [ -f tagui_logging ]; then
```

**Comment by siowyisheng** [comment]
1. I think it's better for you to at least eyeball the changes per PR/feature. Or else, it may be difficult to review all the changes together. I still work on other PRs/features while waiting for your review so no worries.

2. Oh wow I never knew about the `RPA Workshop.md`. Have updated.

3. Have updated.

**Comment by kensoh** [comment]
Ok great, let's do it this way then!

**Comment by kensoh** [comment]
The readme, following section was moved but the 2nd sentence onwards not relevant to that collapsed section. For the note on terminal I think it's good to have somewhere (I've seen too many people using default font sizes on Mac and Windows, which is ridiculously hard to view what's going on with the automations, and maybe they don't know that terminal font size can change) -

Screenshot 2019-12-22 at 10 26 47 PM

**Comment by kensoh** [comment]
For the RPA Workshop file, I saw that there are many formatting changes in the markdown, but visually the rendered file looks the same. Eg changing * to - for italic, lots of empty spaces in tables, removing indentation in collapsed section. Is it because these changes are done by auto-formatter in your IDE? Below is the diff with these formatting changes - 

https://github.com/kelaberetiv/TagUI/pull/652/files#diff-a2a8f9fcfbbee4cead7fd329245dee56

**Comment by kensoh** [comment]
Hi @siowyisheng I added some inputs to above commits -

**Comment by siowyisheng** [comment]
Ah ok I'll edit.

Yup it was the auto-formatting from vscode.

**Pull request merged**
