### PR TITLE
docs: edits samples 1-7 for clarity, friendliness, brevity and more

### PR DESCRIPTION
**Pull request by siowyisheng**
WIP, not for merging.

### CODE REVIEW

**Comment by kensoh** [comment]
Some general comments, before going into each sample -

There is a link from readme to go straight to these sample flows page. If change naming from a_ b_ c_ to 10, 11, 12, the listing will be jumbled up and harder to follow -

Screenshot 2019-12-22 at 10 45 39 PM

Compared to using a, b, c so that listing still remains in sequence -
Screenshot 2019-12-22 at 10 45 47 PM

**Comment by kensoh** [comment]
Take note that the new name for the hastebin sample has to be updated in tagui and tagui.cmd. It's invoked in these runners when users use the upload option, to upload the workflow and results to a free online clipboard for sharing with others. It will supposedly delete uploaded entries in 30 days, but its a free service so don't expect any fulfilling of what's promised or 100% uptime.

**Comment by kensoh** [comment]
I notice that comments are now added after the steps, not before. Is that common for training materials at GA? I would think that comments before code would be the practice for programmers and probably more readable for non-programmers to get a 1-liner of what follows is trying to do.

**Comment by kensoh** [comment]
For 1-yahoo

small typo, `in its` instead
// looks on the web page for an element with 'search-box' in their

It is much easier to follow, but there are information loss, compared to original sample. if want to remove, need to make sure these are covered elsewhere. pros would be digestible chunks to learn, cons will be having to go through many more samples to learn the same number of features.

Examples of stuffs that are gone - note on live step and ask step, rclick, dclick, wait. Also, originally another URL is put there to let users know that they can specify some other URL halfway through the automation to do something else at another webpage. Removing that may lead to users not knowing and think that the first URL is the only page to automate at.

**Comment by kensoh** [comment]
For 2-twitter,

Great new twitter profiles to use as examples! Some loss of info like using JS code for echo (can be put elsewhere such example), and load step example. And also, the bug you found in TagUI which give the problem of the quotation mark problem.

**Comment by kensoh** [comment]
For 3-github, some loss of info eg api step (I don't think it should belong there in the first place, very random. but don't know where to put it.) The examples on download and receive step arguably may be irrelevant if we assume phantom and firefox is no longer going to be used. that may also mean that the steps would be considered for deprecation from API reference.

**Comment by kensoh** [comment]
For 4-conditions, 

Great idea to break up into 2 files to demo conditions and loops separately!

**Comment by kensoh** [comment]
For 5-loops,

Some loss of info on 'infinite loop'

**Comment by kensoh** [comment]
No comments on 6-repositories.

For 7-datatables, a number of examples are removed but have to put somewhere.

**Comment by kensoh** [comment]
Overall, good direction to simplify and made more relatable!

Only thing is loss of info have to be managed somehow, either by creating more samples or some other ways. The reason for packing a lot of information into the samples is so it minimises the chance of new users having to ask on how to use TagUI for some of the steps in these examples. 

Otherwise time taken off to help answer user queries means that the time can't be used for creating new features or fixing bugs. So where I can, I over-provide information instead of under-provide. To make it more scalable when more users use the tool and don't raise issues for simple usage questions.

**Comment by zeddee** [comment]
> I notice that comments are now added after the steps, not before. Is that common for training materials at GA? I would think that comments before code would be the practice for programmers and probably more readable for non-programmers to get a 1-liner of what follows is trying to do.

hey 👋, your friendly tech writer here. was trawling our doc repositories to get a better sense of how we document stuff, and spotted this.

re: comments before code: yeah, usually comments should come before code.

- This makes your comments declarative (do this -> this), which reduces reading load. 
- Also! more importantly, most (if not all) doc generators (if we ever start using them) expect comments to come before code, so that's a good pattern to follow.

i'm working on getting aisg's other projects documented first, as tagui's docs seem the most complete :) but please feel free to ping me if anything comes up

**Comment by siowyisheng** [comment]
this got closed when i renamed v6 branch to develop. i'll just create another PR.

have updated the reference in hastebin. but this really seems like not ideal implementation. samples should be samples and not relied upon on. will revisit in v6/v7.

usually i do comments before blocks of production code, because the comment summarises the code purpose. for shorter lines, i would put the comment on the same line (but tagui can't do this yet). but because this will often be seen by business users, the simple 'code' itself will probably be less confusing than the `//` of the comments. but i'm not sure yet which is better.

for the numbering, i'll do 01, 02, 03...

> Examples of stuffs that are gone - note on live step and ask step, rclick, dclick, wait. Also, originally another URL is put there to let users know that they can specify some other URL halfway through the automation to do something else at another webpage. Removing that may lead to users not knowing and think that the first URL is the only page to automate at.

i believe the first script should be as simple as possible, and not cover any non-core features (like ask, rclick, dclick, navigating to another url in the middle of a flow). non-core features should come in later samples. for VERY non-core features/api, it's fine to not have samples imo, like `rclick`, `dclick`.

`live` will be implemented as a command and documented elsewhere. the use of `live` in scripts will be introduced later as a non-core command.


i'll continue to mindfully consider what to include/exclude from each sample. i'll definitely produce other docs for learning tagui too, and consider what part the samples will play into the whole scheme of it.

**Comment by kensoh** [comment]
Hi @zeddee thanks for your inputs! As TagUI is part of AIM's offerings, let us know if there are some documentation guidelines to follow so that docs across various tools project a consistent experience for users.

Hi @siowyisheng thanks for sharing your considerations and I second your thoughts!

**Pull request closed without merging**
