### PR TITLE
Readthedocs page

### PR DESCRIPTION
**Pull request by siowyisheng**
major overhaul and upgrading of docs

### CODE REVIEW

**Comment by kensoh** [comment]
Looks great!!

Putting down some comments, I've gone through the repo structure and installation section only -
- [samples folder](https://github.com/kelaberetiv/TagUI/tree/readthedocs_page/samples) look like not yet done, may have to exclude from the PR, as files won't work without the .tag extension, also the temporary generated files, text output files and image snapshots from running the samples should be removed
- https://tagui.readthedocs.io/en/readthedocs_page/setup.html - consider dropping full-stop at end of the point I think it's a more common convention for points list, to discuss more
- https://tagui.readthedocs.io/en/readthedocs_page/setup.html - for mac/Linux after linking the line `./tagui your_tagui_path/tagui/src/samples/1_yahoo chrome` should be just `tagui your_tagui_path/tagui/src/samples/1_yahoo chrome` without the ./ in front
- the _build and _static folders are they generated files? if yes should put in .gitignore to exclude from code base in repo. unless readthedocs require them to be stored in repo in order to host the webpage, to chat more tomorrow..

**Comment by kensoh** [comment]
For FAQ, the line
>Each line is a row of values. The values are split into different columns by commas ,, which is CSV stands for Comma Separated Values.

should be something like that
>Each line is a row of values. The values are split into different columns by commas `,`. CSV stands for Comma Separated Values.

or missing the `why`
>Each line is a row of values. The values are split into different columns by commas `,`, which is why CSV stands for Comma Separated Values.

**Comment by siowyisheng** [comment]
Ah yup thanks for checking through!

**Comment by kensoh** [comment]
For Tools, TagUI for Python has been renamed RPA for Python, text to change would be the name, pip install rpa, and the URL - https://github.com/tebelorg/RPA-Python

**Comment by kensoh** [comment]
For Advanced Concepts,

This looks like a typo
>type \`\`email\`\` as my_email@email.com

and should be
>type \`email\` as my_email@email.com

For Object repositories, maybe can write something on the value of why use it. For eg, reusability of objects definitions across different workflows, easier maintenance to update changes at 1 place instead of making the changes in many flows.

For the Visual Automation tricks, consider reviewing the verbiage of removing background because it may not be clear that the meaning is to make the background transparent and could mean remove the background and keep it colourless like white colour.

**Comment by kensoh** [comment]
For Main  Concepts,

>tagui c:\tagui\samples\1_yahoo.tag chrome

Should now be below as Chrome is default
>tagui c:\tagui\samples\1_yahoo.tag

For run with double-click, can add something that say that the shortcut can be moved to your Desktop folder for easy access, otherwise users may think that it has to be at the location of the flow file in order to use it.
>This creates a shortcut to run your flow just by double clicking the shortcut. The shortcut is in the same folder as your flow.

For below, don't need chrome
>tagui https://raw.githubusercontent.com/kelaberetiv/TagUI/master/src/samples/1_yahoo chrome

For below section, consider also introducing exist() which will keep waiting until timeout for the element to appears vs present() which will return true or false the moment the function is called
>if !present('some-element')
{
  https://tagui.readthedocs.io/
}

For clipboard(), consider including its other use case, to assign text or variable to clipboard. The common use case for this is put a large chunk of text and then do keyboard [ctrl]v to paste instantly, instead of using type which may be considered too slow to type character by character for some user use cases.

**Comment by kensoh** [comment]
Have reviewed all except References which you are WIP. After reviewing References, I'll see if anything else good to be added. Thanks!!

**Comment by siowyisheng** [comment]
Changes made in response to your comments, and references section updated.

**Comment by siowyisheng** [comment]
@kensoh do check out the changes made when you have time!

**Comment by kensoh** [comment]
Ok! Not so soon, was looking at some new user issues. And now running through the messages in whatsapp on the BCP thing. Priority would be making automation, if really needed, for the team on temperature taking, as that has a larger impact.

**Comment by kensoh** [comment]
- [x] samples folder ok, to review again before publishing after merging all PRs. some features would make the samples not work, for eg the one one echo check dump write will change existing syntax
- [x] full stop at end of list is not dropped https://tagui.readthedocs.io/en/readthedocs_page/setup.html but that's ok as long consistent formatting style is used
- [x] part on `tagui your_tagui_path/tagui/src/samples/1_yahoo chrome` without ./
- [x] _build folder removed and _static remained for documentation assets
- [x] csv grammar typo
- [x] RPA for Python new name and URL
- [x] fix type `email` as my_email@email.com
- [x] verbiage on object repository and visual automation transparency
- [x] main concept changes
- [ ] review references
- [ ] review whole documentation again for changes not yet seen

Main concepts - 
- The line `tagui https://raw.githubusercontent.com/kelaberetiv/TagUI/master/src/samples/1_yahoo` should now also be with .tag `tagui https://raw.githubusercontent.com/kelaberetiv/TagUI/master/src/samples/1_yahoo.tag`
- I think the line clipboard(`long_text`) will not work without ; at the end

**Comment by kensoh** [comment]
Hi @siowyisheng I've reviewed and posted my findings above. Thanks a lot for the huge amount of work that went into making this revamp!! Later this week, when I'm less sleep-deprived, I'll look again with fresh eyes.

**Comment by kensoh** [comment]
Hi @siowyisheng, done another round of review,
adding on to the eariler observations https://github.com/kelaberetiv/TagUI/pull/709#issuecomment-585108176,

Landing page -
- https://tagui.readthedocs.io/ redirects to https://tagui.readthedocs.io/en/latest/ which is a dummy template page. is it possible to redirect to the real docs home page https://tagui.readthedocs.io/en/readthedocs_page/index.html#? Or is it after published the content will automatically show up in latest. Rationale is some people may share or type that short URL and lands on a dummy template page.
- landing page `An open-source, cross-platform, command-line RPA tool that allows you to automate your desktop web, mouse and keyboard actions easily.` missing a , between desktop and web

Installation - 
- for versioning consider using v6.0 since minor releases is not used so far. Only during publishing new release it is mandatory to key in the 3rd digit at the end. Same for the help and version when type `tagui` without options
- for `tagui c:\tagui\src\samples\1_yahoo chrome`, no longer need chrome and will be 1_yahoo.tag
- same above for macOS/Linux
- for https://tagui.readthedocs.io/en/readthedocs_page/setup_troubleshooting.html#troubleshooting-windows for `You may need to install PHP separately on Linux.` consider elaborating to something like `You will need to install PHP separately on Linux, if entering the command php -v shows an error.`

Main concepts -
- `tagui my_flow.tag deploy` becomes `tagui my_flow.tag -deploy`
- `tagui my_flow.tag headless deploy` becomes `tagui my_flow.tag -headless -deploy`
- `tagui my_flow.tag headless` -> `tagui my_flow.tag -headless`
- typo ` which has “Getting started” as it’s` should be `its`
- `row_count = count('row')` should still be `row_count = count(row)`
- 2 instances of `echo mouse_xy()` now is echo \`mouse_xy()\`

Advanced concepts - 
- consider having an example `for n from 1 to infinity`

Reference -
- `Wait for user confirmation before continuing. The user must enter “done” before the flow continues.` consider adding something that says users can enter steps and JavaScript code to test interactively.
- for table step, consider saying something that suggests that it works only for simple HTML table. (complex tables that are not a columns x b rows will not work. for eg if some cells are merged)
- should be `finish` instead of `end` for js, py, r, vision, dom, run steps
- new options, -deploy, -nobrowser, and options there would now have - prefix

Tools -
- i missed that `TagUI For Python is a Python API for TagUI.` should be RPA for Python is a Python API for TagUI.`

**Comment by siowyisheng** [comment]
Thanks @kensoh will edit!

**Comment by kensoh** [comment]
Adding on stuffs that are missing from original readme,

- some summary statement of the features, currently -
>automate Chrome in visible / invisible mode
>visual automation of websites and desktop
>write in 20+ human languages & JavaScript
>Chrome extension for recording web actions
>Python & R integrations for machine learning
- somewhere to link to sample flows for users to see examples

- `If you Ctrl+C to break a TagUI automation, you can use tagui/src/end_processes command (for macOS/Linux) or end_processes.cmd (for Windows) to kill any dead processes of TagUI integrations (Chrome, SikuliX, Python etc)`

- `Make sure TagUI's Chrome browser is set to 100% zoom. As TagUI mimics the user mouse-clicks at the (x,y) coordinates of web elements, using a different zoom level will cause clicks to be triggered at wrong locations.`

- Section on native languages - https://github.com/kelaberetiv/TagUI#native-languages

- architecture diagram, good for people who are building stuffs on TagUI

- developers section, particularly API, Files, Security details sections
- will be good to have credits section or dependencies / built-using somewhere, as best open-source practice. for my name there, it was to credit for funding and developing it to v3 from 2016 Jul - 2017 Nov before I join AISG in Dec 2018. For the others CasperJS, PhantomJS, SlimerJS I think it would be good to include at least the project names but ideally the authors.
- also need the NRF footer (now in master readme)

One way if you feel that above are not needed is to link from somewhere in the new readme to the pre_v6 readme, and from your readme you can write a 1-line summary `for xxx, yyy, zzz, refer to the Pre-v6 readme` something along that lines.

**Comment by kensoh** [comment]
Thanks @siowyisheng ! Added some new comments on the deltas I found for consideration.

**Comment by siowyisheng** [comment]
@kensoh have updated the samples using the ones from earlier.

You may want to read the earlier thread on this. Some suggestions from there seem good.
https://github.com/kelaberetiv/TagUI/pull/657

**Comment by kensoh** [comment]
@siowyisheng I've updated the samples to v6 syntax. A number of things to highlight - 

The 2_twitter sample is updated but I think Twitter changed web layout, can you update to work for the new Twitter website?

For 7_datatable sample, the form_data.csv is missing I added it from your other branch, also changed the 3rd row to peter parker to avoid repeating same data as row 1.

For 8_test sample, there is a bug spotted and change made in tagui_parse.php. There is a code to remove empty lines in the test mode, but that will mess up with the code in escape_bs() function, thus remove that line of code.

For 9_hastebin, updated src/tagui and src/tagui.cmd to point to new location and filename, and use the correct new runtime options. However the hastebin.com webpage one of the button now is disable to convert to raw text. Not sure is temporary or permanent.

For the suggestions from https://github.com/kelaberetiv/TagUI/pull/657, you can look through and make the changes directly to the samples as you own the docs and samples you can decide.

Lastly, need to make all the samples consistent to the format you want. You decide to stick with comments first before code or the new format comments after code in your updated samples.

**Comment by siowyisheng** [comment]
Thanks a lot Ken! Ya I'll update the docs from here.

**Comment by kensoh** [comment]
@siowyisheng made a commit above on a typo in tagui.cmd. Also, my local codebase has differences from develop branch. After this PR is merged into develop and conflicts resolved, we can see if anything else has been missed to add on.

**Comment by siowyisheng** [comment]
have resolved the merge conflicts. will do one last check through later before final merge and release cut.

further docs updates will be in a new branch

**Pull request merged**
