### PR TITLE
chrome hack on windows using php - fix and more robust

### PR DESCRIPTION
**Pull request by kensoh**
Draft PR to be validated

### CODE REVIEW

**Comment by kensoh** [comment]
To use following instead, somehow double quotes is required to enclose the PHP commands.

```
rem hack chrome to prevent ended unexpectedly message
set "chrome_pref=chrome\tagui_user_profile\Default\Preferences"
if exist "%chrome_pref%" (
	php -q -r "file_put_contents('%chrome_pref%',str_replace('\"exited_cleanly\":false','\"exited_cleanly\":true',file_get_contents('%chrome_pref%')));" > nul 2>&1
	php -q -r "file_put_contents('%chrome_pref%',str_replace('\"exit_type\":\"Crashed\"','\"exit_type\":\"Normal\"',file_get_contents('%chrome_pref%')));" > nul 2>&1
)
```

**Comment by kensoh** [comment]
Thanks @siowyisheng for merging the other 2 PRs!

This PR I'm comfortable for you to review and test. Looks good to be finally able to hack Chrome to get rid of the irritating popup message. Also this is on tagui_user_profile, no impact to user's own Chrome preferences.

**Comment by siowyisheng** [comment]
will test this thanks!!!

**Comment by kensoh** [comment]
Thanks! Finally can get rid of this irritating popup.

**Comment by siowyisheng** [comment]
Tested and working consistently.

**Pull request merged**
