### PR TITLE
added get attribute feature as attribute step, example - attribute locator | at…

### PR DESCRIPTION
**Pull request by sachin1004**
Hi Kensoh,

I was looking for a way to get attribute values to validate error scenarios, where css classes are added to element. So added this feature to return attribute value of a node.

### CODE REVIEW

**Comment by kensoh** [comment]
Hi @sachin1004 this is a great PR! Some notes below from looking through the code, which I could add as a follow-up commit after this PR. I hope to be able to add this to the codebase, but before that, I want to ask you on 2 things.

For your use case, are you able to use `/@attribute` with read step [for example this issue](https://github.com/kelaberetiv/TagUI/issues/427)?

Do you have other use cases where reading attribute of a web element is required? Am hesitant to add this into codebase because of above using `/@attribute` directly using XPath, and normal process automation by users would not be accessing values of attributes of the web elements.

**tagui_header.js**
line 815 - substr() used as function instead of .substr()
line 1142 - if implemented, live mode support should be added

**tagui_parse.php**
line 465 - typo 'timeout' string used instead of 'attribute'
line 1134 - | could be used in XPath as or, and would lead to error
line 1141 - should have ways to improve for eg using ' to ' instead of 'to'

**Comment by kensoh** [comment]
Other than above thoughts, your understanding of the logic for TagUI is correct 💯👏

Internal note - for new step, would need to update the language translation engine and dictionaries to support step in other languages. translate.php, translate() in tagui_header.js and dictionaries in src/languages folder.

**Comment by sachin1004** [comment]
@kensoh Thanks for replying. We have not tried with xpath @attribute you mentioned. In our use case, when we are testing for negative scenarios, where we mostly use css selector to find element. This was of real help. So i thought this would be helpful. 

I didn't realize that xpath could have "|" in it, i will try to make that change.  I will try to add it in live_step and translation file also.

I will commit and raise a PR again, if you think this step would help others.

**Comment by kensoh** [comment]
Hi @sachin1004 I've thought over it. The technical issues above in tagui_header.js and tagui_parse.php, updating of language translation engine and dictionaries can be addressed with some discussion and some effort of work. But the main problem with implementing this new step is there are currently 2 ways to address a web element attribute.

First, by using XPath and ending the XPath with `/@attribute`. Second, this can be retrieved using the dom step by querying that web element's attribute directly using its CSS selector. Below shows both ways trying to retrieve the class attribute of the search bar in Google webpage.

The type step is to confirm that the identifier used for the search bar is correct. Both will show the class attribute correctly. For my browser and region, it shows `gLFyf gsfi`.

```
https://google.com
type //*[@name="q"] as 123
read //*[@name="q"]/@class to element_class
echo element_class
```

```
https://google.com
type [name='q'] as 123
dom return document.querySelector('[name="q"]').getAttribute("class")
echo dom_result
```


Adding a new step to do that in the short term will benefit a small number of users with this edge, because users can use attribute step to do this. But in the long term, that is bad for this small group of users and the rest of the user. Because there are many other JavaScript stuffs that can be done with TagUI `dom` step.

If different things for less commonly use case gradually get added as new TagUI steps, over time the number of TagUI steps will double. But that has little advantage for the user because user will have to remember and choose from a larger list of steps to use. Versus using a small set of steps that allows user to do the same things.

Because of above, I will not add a new attribute step from your PR. However, I appreciate the work that you have done and for sharing it. So I'll raise a new issue to commit this PR and then follow-up with a PR to roll-back. This allows your code in this PR to be in the commit history for further reference if there is a need to revisit this. This also adds you into the list of contributors on TagUI home page - https://github.com/kelaberetiv/TagUI/graphs/contributors

Thanks for raising this!!

**Pull request merged**
