### PR TITLE
update tagui.cmd with secondary chrome location

### PR DESCRIPTION
**Pull request by kensoh**

### CODE REVIEW

**Comment by kensoh** [comment]
Hi @siowyisheng for your review and test on Windows. Closing basecamp issue to follow-up here.

**Comment by siowyisheng** [comment]
Somehow can't get this working. Even after removing the normal chrome directory and placing a working chrome in the new target directory, the script doesn't run. And it fails silently too.

**Comment by siowyisheng** [comment]
Not sure how to proceed on this.

**Comment by kensoh** [comment]
I'm guessing that this is expected behaviour, if your Chrome is not installed really installed in %LOCALAPPDATA% folder just moving the folder there may not let Chrome work, as other Windows registry info will still point to the old original location.

The code change for this PR adds below line to check if the original location is not found, it will change to point to below location. But maybe can't test unless we find a Windows laptop that Chrome is installed here.

```
if not exist "%chrome_command%" set chrome_command=%LOCALAPPDATA%\Google\Chrome\Application\chrome.exe
```

If can't have a Windows laptop with Chrome at this location to test, can you add another line below you tagui.cmd to echo the command to at least check if it is pointing to a correct new location?

```
if not exist "%chrome_command%" set chrome_command=%LOCALAPPDATA%\Google\Chrome\Application\chrome.exe
echo %chrome_command% 
```

The secondary location seems to be at %LOCALAPPDATA%, from
- https://superuser.com/questions/329112/where-are-the-user-profile-directories-of-google-chrome-located-in
- https://superuser.com/questions/545351/install-google-chrome-to-appdata-local-google-chrome-application
- https://stackoverflow.com/questions/40674914/google-chrome-path-in-windows-10

As long as after the change, the echo points to the correct secondary location, and that for Windows with Chrome in the original program files location work (for eg your laptop), then the PR should be ok to commit to develop.

You can do other checks if possible to see if Chrome is invoked in the secondary location, or if you try to invoke it manually from command line in the secondary location on your laptop, does it not invoke, in the same way as TagUI does.

**Comment by siowyisheng** [comment]
it would need to be on windows 7 I think. That's where chrome is installed
at that path.

**Comment by kensoh** [comment]
I see.. Do you think anyone in office has a Windows 7 computer to test?

Will be tricky to find, since AISG main hiring only started in 2018.

**Comment by siowyisheng** [comment]
Will be difficult to find. Asked a few people but don't have.

**Comment by kensoh** [comment]
I see, in that case 1 way to test whether this change works is you try to do an echo statement like the above example. If you moved Chrome to the fake folder and the echo statement shows the correct chrome.exe location, and if it is in original folder, it shows the original folder location, then the code change is working as intended.

The assumption is if the chrome.exe is in other folder calling the chrome.exe command should work. If that doesn't work it isn't really something TagUI can do anyway as that is some problem with Chrome installation in that folder that can't be invoked from command line. But in order to get feedback on whether that works, need to implement first.

I'm good with committing to develop branch and also committed to the fork I maintain. But closing the PR for now until you are comfortable to implement.

**Comment by kensoh** [comment]
backup of the code changes in src\tagui.cmd before deleting branch -

```
rem configure default command location to launch Chrome on Windows
set chrome_command=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

rem fallback to backup location for some users who cannot install Chrome system-wide
if not exist "%chrome_command%" set chrome_command=%LOCALAPPDATA%\Google\Chrome\Application\chrome.exe
```

```
		echo ERROR - cannot find Chrome at "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
 		echo ERROR - or at user folder "%LOCALAPPDATA%\Google\Chrome\Application\chrome.exe"
```

**Pull request closed without merging**
