### PR TITLE
Positive test cases and signature

### PR DESCRIPTION
**Pull request by kensoh**

### CODE REVIEW

**Comment by kensoh** [comment]
Hi @siowyisheng done with the positive test cases and signature. For review before merging.

**Comment by siowyisheng** [comment]
Strange, I'm getting this.
image

**Comment by kensoh** [comment]
Oh you are not using the latest master which has this indentation fix -

https://github.com/kelaberetiv/TagUI/commit/9c328b1aae5d15fbbac0df2058aca79a250d6fff

**Comment by siowyisheng** [comment]
Ah right I needed to rebase onto master.

All looks good. Only difference is I have some windows stuff like this. Which should be ok. Merging.
image

**Comment by kensoh** [comment]
Thanks! I assume you mean that the generated signature is different. Interesting, the code that generates this should also be executed on other OS, not sure why but should be ok.

**Pull request merged**
