### PR TITLE
Consistent string and var for steps echo, dump, write, check

### PR DESCRIPTION
**Pull request by kensoh**
@siowyisheng raising draft PR for your review and testing. This change is quite pervasive, will need to work together on some iterations to cover edge cases thoroughly.

### CODE REVIEW

**Comment by siowyisheng** [comment]
to continue to test separately

**Comment by siowyisheng** [comment]
Edge cases include:
1. user wants to echo single quote

**Comment by kensoh** [comment]
```echo 123'456``` doesn't work but we don't really expect users to escape since this is not enclosed within quotation marks. Need to explore more edge cases like these and fix.

**Comment by kensoh** [comment]
@siowyisheng initial finding turns out the behaviour with single quote is consistent. `echo 123'456` throws error just as `type q as 123'456`. Using double quote works for both and using \\' works for both. If this is to be fixed, then the behaviour for other steps should also be fixed.

**Comment by kensoh** [comment]
Hi @siowyisheng this looks good after doing some tests. For your checks.

1 potential improvement is whether to make single quote usable without the escape character, though this is the same behaviour for all steps. So we can evaluate that separately if that makes sense.

I thought over whether this change can be made backward compatible by detecting input passed in from the script. It seems like it isn't possible to do it deterministically. There isn't a fool proof way to detect for sure whether user is typing quotes to mean string or really want to echo a quotation mark. Similarly for `'+variable+'` structure. If use regex or some matching of this form to 'intelligently' recognise old format, what if user really wants to echo this string as a string.

This seems like a change that cant be made backward compatible.

Another idea is we can evaluate all those changes in v6 and create some migration script to convert old scripts to new scripts format (eg .tag extension, formatting used by echo, dump, write, check). This could remove user friction substantially for scripts that uses these steps a lot.

**Comment by kensoh** [comment]
Was reading your new docs and saw this.. It seems like for conditions and defining of variables there will still be 'inconsistency' as text needs to be enclosed in quotation marks and variables with backticks. Hmm... Can't really remove the need for quotations marks is that correct? For eg below, if remove quotation marks then it can introduce ambiguous situations to tell which is operator which is text.

```
if url() contains "success"
{
  click button1.png
  click button2.png
}
```

**Comment by kensoh** [comment]
As discussed, implementing as planned. Least of all evils.

**Comment by kensoh** [comment]
Following throws error, initial finding seems to be the call for `get_text_for_sikuli($input_params)` not generating proper JS syntax for if the parameter is a variable -

```
a = '1'
keyboard `a`[enter]
```

**Comment by kensoh** [comment]
Following throws error, initial finding seems to be the call for `get_text_for_sikuli($input_params)` not generating proper JS syntax for if the parameter is a variable -

```
a = '1'
keyboard `a`[enter]
```

**Comment by siowyisheng** [comment]
tested and LGTM

**Comment by siowyisheng** [comment]
tested and LGTM

**Pull request merged**
