### PR TITLE
#750 - exit gracefully if .tag extension not used

### PR DESCRIPTION
**Pull request by kensoh**

### CODE REVIEW

**Comment by kensoh** [comment]
Hi @siowyisheng bug found with .tag on Windows, spotted by user in #750. The log files are being converted from Linux to Windows format without checking that they exist. This was missed when testing on Windows for only positive test but not negative test.

**Comment by ba700113** [comment]
I changed the extension to .tag and the error didn't show.
But before the script will run, its opens Chrome first. my script doesn't even need chrome
Is this  a bug taguiV6?
Can you help me resolve it. 
Thank you

**Comment by siowyisheng** [comment]
@ba700113 If your script doesn't use chrome, you can run it with `tagui my_flow.tag -nobrowser` or `tagui my_flow.tag -n`

**Comment by ba700113** [comment]
this is a different question, how do i get a CSV report after my test run?
in my script i put report at the every script i call in my batch file. but
it doesn't create a CSV for me
example: ..\tagui desktop.tag report

**Comment by kensoh** [comment]
In v6 the options has a dash prefix, for eg `tagui desktop.tag -report` or `tagui desktop.tag -r`

**Pull request merged**
