### PR TITLE
Update issue templates - pending implementation later on

### PR DESCRIPTION
**Pull request by siowyisheng**

### CODE REVIEW

**Comment by kensoh** [comment]
Thanks @siowyisheng let me chew over it! The part on bug report and label can be too specific, because issues raised may be a general query, bug or feature request. And to a user who doesn't know the planned design, everything that doesn't work is a bug, which isn't true. The part on version maybe i'll add something to type tagui without parameters to see the version.

**Comment by kensoh** [comment]
Have thought over but can't bring myself to implementing this now. Maybe later on when you've taken over as primary support for TagUI. Rationale is having a template saves us some time at the expense of increasing user friction.

For the time being, will still like to to optimise the user support experience. Think that is an impt differentiator to any other automation tools, open-source or commercial community editions. So not optimising this can be detrimental.

PR can keep open until later on for merging.

**Comment by kensoh** [comment]
After a good night sleep, I think there should be some verbiage that improve user experience at the same time does not increase user friction when raising issue. Let me think over a draft and put here for discussion.

Assuming the common goal is the fastest resolution to a query or problem, then replication step is absolutely impt. OS not as impt as most features are common and from the script file name paths can infer. Version thinking thru, also not impt. If it's an issue which obviously is fixed we can just recommend installing cutting edge or the new packaged release.

**Comment by siowyisheng** [comment]
OK sounds good.

**Comment by kensoh** [comment]
@siowyisheng - new iteration to streamline, i'll test on dummy repo and iterate again

**Comment by kensoh** [comment]
@siowyisheng I made some testing and revision to streamline. No need to ** because markdown is not rendered within the comment enclosure. Below is my final iteration.

```
---
 name: TagUI issue template
 about: Raise an issue for queries, bugs or suggestions
 title: ''
 labels: ''
 assignees: ''

 ---

 <!-- How can we replicate the issue (include your TagUI code)? -->
```

However, after testing, I realise this adds additional user friction when raising new issues. After clicking new issue, user will see below screen, and need to click on the template button to go to the usual new issue page. I feel that this make sense only if there are multiple templates in future (eg IDE, core, Orchestrators etc). Otherwise for now add new additional click for every new issue, in exchange to inform user to include replication steps.

Screenshot 2020-01-03 at 11 11 48 AM

I'll close the PR, but above info can be retain for future use. Feel free to reopen if you want to discuss more.

**Pull request closed without merging**
