### PR TITLE
feat: creates tagui_global.csv file for user and flows folder

### PR DESCRIPTION
**Pull request by siowyisheng**

### CODE REVIEW

**Comment by siowyisheng** [comment]
1. creates the tagui_global.csv for easy editing
2. creates flows folder
3. moves sample flows to the tagui/flows/samples folder
4. fixes 1_yahoo.tag

**Comment by kensoh** [comment]
Thanks @siowyisheng merged! I modified tagui and tagui.cmd to cater the upload option for new location of the 8_hastebin file, with .tag extension and the new options dash and nobrowser.

Other than the Yahoo samples, other samples need to be changed too to the new syntax. There are a few that uses echo step. We can do that before publishing v6.

I think you are making changes to the samples, if the changes are done already I can also look through them to make them v6 compliant.

**Comment by siowyisheng** [comment]
Yea i realised that the samples are also being changed in the readthedocs branch. I'll resolve the merge conflicts. I think it's better to do all the sample changes there.

**Comment by kensoh** [comment]
Sure let's do that way!

**Pull request merged**
